[package]
name = "Driver"
version = "0.1.0"
authors = ["Austin Haskell <austinoliverhaskell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.79"
gpio = "0.4.1"
tmc2209 = "0.1.0"