[package]
name = "SVG_Art_Generator"
version = "0.1.0"
authors = ["austi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.8.0"
rand = "0.7.3"